Updated disable_write to be consistent with ONETEP 5

diff --git a/utils/update_case_file b/utils/update_case_file
--- a/utils/update_case_file
+++ b/utils/update_case_file
@@ -1,64 +1,37 @@
 #!/bin/bash
+# Simple script for updating a variable entry in a ONETEP .dat file
+# Written by Edward Linscott May 2019
 
+# If an error occurs, exit immediately with an error code
+set -e
+
+variable="$1"
+value="$2"
+datfile="$(ls *.dat)"
+updated_entry="$variable : $value"
+
+# Find match, being careful to avoid partial matches (e.g. "ldos_smear" matching "dos_smear")
+# In order to preserve double spacing, briefly reset IFS
 IFS='%'
-variable=" "$1
-ll=$2
-zz=`ls *.dat`
-TMPFILE=./tmp56131291
+match=$(cat $datfile | awk -v var="$variable" -F" " '$1 == var')
+n_matches=$(echo $match | wc -l)
 
-sed 's/^/ /' $zz > $TMPFILE
-mv $TMPFILE $zz
-
-echo "------------------------------------------------"        >> updating_variables
-echo "CASE FILE               :  " ${zz}                       >> updating_variables
-echo "VAR                     :  " $variable                   >> updating_variables
-echo "ADDING VAR IF NECESSARY :  "                             >> updating_variables
-grep $variable $zz  > /dev/null 2>&1 || echo "$variable : XX " >> ${zz}   
-echo "VAR PRESENT?            :  " cat *.dat | grep $variable  >> updating_variables
-echo " NAME OF TMP FILE       :  " ${TMPFILE}                  >> updating_variables
-echo "------------------------------------------------"        >> updating_variables
-echo " PROCESS DETAILED BELOW :  "                             >> updating_variables
-echo "CHECKING FOR DUPLICATES :  "                             >> updating_variables
-dup=`grep $variable $zz |wc -l`
-if [ $dup -eq 1 ]
-then
- echo " ONLY ONE INSTANCE OF THIS FLAG           " >> updating_variables
+if [ -z "$match" ]; then
+   # For no matches, append to end of file
+   echo $updated_entry >> $datfile
+elif [ $n_matches -eq 1 ]; then
+   # For one match, do in-place replacement
+   sed -i "s/$match/$updated_entry/g" $datfile
 else
- echo " TWO OR MORE ENTRIES OF THIS FLAG         " >> updating_variables
- echo " KEEPING THE FIRST ONE "                    >> updating_variables
- backup=`grep $variable $zz | head -n 1`
- stringtoremove=`grep $variable $zz | tail -1 |awk '{print $1}'`
- echo "string to remove : " $stringtoremove        >> updating_variables
- sed  's/ '${stringtoremove}'.*//g' $zz  > ${TMPFILE}
- mv  ${TMPFILE} $zz
- echo $backup >> $zz 
+   # For multiple matches, exit with error
+   echo "ERROR: found multiple ($n_matches) entries for $variable in $datfile"
+   # Restore IFS
+   unset IFS
+   exit 1
 fi
 
-echo "NOW VAR PRESENT? "                     >> updating_variables
-grep $variable $zz                           >> updating_variables
+# Print summary
+echo "$variable set to $value in $datfile"
 
-k=`cat *.dat | grep $variable`
-it=`echo $k |awk '{print $3}'`
-echo " REPLACING " $it "WITH " ${ll}  >> updating_variables
-
-new_line=`echo $k | sed 's/'${it}'/'${ll}'/g'` 
-filename=`ls *.dat`
-
-echo "old iter = " $it          >> updating_variables
-echo "new iter = " $ll          >> updating_variables
-echo "k        = " $k           >> updating_variables
-echo "new line = " ${new_line}  >> updating_variables
-
-ttt='s/'${k}'/'${new_line}'/g'
-echo "SED ARGUMENT IS : " $ttt  >> updating_variables
-sed $ttt $filename >  ${TMPFILE}
-mv  ${TMPFILE} $filename
-
-sed 's/^ //' $filename > $TMPFILE
-mv $TMPFILE $filename
-
-echo "ALL DONE ......                                 " >> updating_variables
-echo " "                                                >> updating_variables
-echo "------------------------------------------------" >> updating_variables
-
-
+# Restore IFS
+unset IFS
